/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ClientId = IDL.Text;
export const Time = IDL.Int;
export const Client = IDL.Record({
  'id' : ClientId,
  'name' : IDL.Text,
  'createdAt' : Time,
  'isActive' : IDL.Bool,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
  'mapLocation' : IDL.Text,
});
export const FinancialEntryId = IDL.Nat;
export const FinancialEntryType = IDL.Variant({
  'expense' : IDL.Null,
  'income' : IDL.Null,
});
export const FinancialEntry = IDL.Record({
  'id' : FinancialEntryId,
  'entryType' : FinancialEntryType,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Nat,
});
export const InvoiceId = IDL.Nat;
export const Invoice = IDL.Record({
  'id' : InvoiceId,
  'clientId' : ClientId,
  'clientName' : IDL.Text,
  'date' : IDL.Text,
  'isPaid' : IDL.Bool,
  'totalAmount' : IDL.Nat,
  'nextMaintenanceDate' : IDL.Text,
  'services' : IDL.Vec(IDL.Text),
});
export const JobId = IDL.Nat;
export const JobStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Job = IDL.Record({
  'id' : JobId,
  'status' : JobStatus,
  'clientId' : ClientId,
  'clientName' : IDL.Text,
  'date' : IDL.Text,
  'serviceDescription' : IDL.Text,
  'notes' : IDL.Text,
  'price' : IDL.Nat,
});
export const Garden = IDL.Record({
  'photoUrls' : IDL.Vec(IDL.Text),
  'clientId' : ClientId,
  'toolsRequired' : IDL.Text,
  'grassType' : IDL.Text,
  'sizeM2' : IDL.Float64,
  'observations' : IDL.Text,
  'avgWorkTimeHours' : IDL.Float64,
  'terrainType' : IDL.Text,
});
export const ScheduleId = IDL.Text;
export const MaintenanceSchedule = IDL.Record({
  'id' : ScheduleId,
  'frequencyDays' : IDL.Nat,
  'clientId' : ClientId,
  'isActive' : IDL.Bool,
  'notes' : IDL.Text,
  'lastDate' : IDL.Text,
  'nextDate' : IDL.Text,
});
export const ProspectId = IDL.Nat;
export const ProspectStatus = IDL.Variant({
  'quoteSent' : IDL.Null,
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const Prospect = IDL.Record({
  'id' : ProspectId,
  'status' : ProspectStatus,
  'name' : IDL.Text,
  'serviceRequested' : IDL.Text,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
  'quoteDate' : IDL.Text,
});
export const QuoteId = IDL.Nat;
export const QuoteStatus = IDL.Variant({
  'pending' : IDL.Null,
  'sent' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const Quote = IDL.Record({
  'id' : QuoteId,
  'status' : QuoteStatus,
  'clientId' : ClientId,
  'clientName' : IDL.Text,
  'date' : IDL.Text,
  'serviceDescription' : IDL.Text,
  'notes' : IDL.Text,
  'price' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createClient' : IDL.Func([Client], [], []),
  'createFinancialEntry' : IDL.Func([FinancialEntry], [FinancialEntryId], []),
  'createInvoice' : IDL.Func([Invoice], [InvoiceId], []),
  'createJob' : IDL.Func([Job], [JobId], []),
  'createOrUpdateGarden' : IDL.Func([Garden], [], []),
  'createOrUpdateMaintenanceSchedule' : IDL.Func([MaintenanceSchedule], [], []),
  'createProspect' : IDL.Func([Prospect], [ProspectId], []),
  'createQuote' : IDL.Func([Quote], [QuoteId], []),
  'deleteClient' : IDL.Func([ClientId], [], []),
  'deleteFinancialEntry' : IDL.Func([FinancialEntryId], [], []),
  'deleteInvoice' : IDL.Func([InvoiceId], [], []),
  'deleteJob' : IDL.Func([JobId], [], []),
  'deleteProspect' : IDL.Func([ProspectId], [], []),
  'deleteQuote' : IDL.Func([QuoteId], [], []),
  'getAllActiveSchedules' : IDL.Func(
      [],
      [IDL.Vec(MaintenanceSchedule)],
      ['query'],
    ),
  'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getAllJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClient' : IDL.Func([ClientId], [Client], ['query']),
  'getEntriesByType' : IDL.Func(
      [FinancialEntryType],
      [IDL.Vec(FinancialEntry)],
      ['query'],
    ),
  'getGardenByClient' : IDL.Func([ClientId], [Garden], ['query']),
  'getInvoice' : IDL.Func([InvoiceId], [Invoice], ['query']),
  'getJob' : IDL.Func([JobId], [Job], ['query']),
  'getProspectsByStatus' : IDL.Func(
      [ProspectStatus],
      [IDL.Vec(Prospect)],
      ['query'],
    ),
  'getQuoteByStatus' : IDL.Func([QuoteStatus], [IDL.Vec(Quote)], ['query']),
  'getUpcomingMaintenance' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(MaintenanceSchedule)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markInvoiceAsPaid' : IDL.Func([InvoiceId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateClient' : IDL.Func([Client], [], []),
  'updateFinancialEntry' : IDL.Func([FinancialEntry], [], []),
  'updateJob' : IDL.Func([Job], [], []),
  'updateJobStatus' : IDL.Func([JobId, JobStatus], [], []),
  'updateProspect' : IDL.Func([Prospect], [], []),
  'updateProspectStatus' : IDL.Func([ProspectId, ProspectStatus], [], []),
  'updateQuote' : IDL.Func([Quote], [], []),
  'updateQuoteStatus' : IDL.Func([QuoteId, QuoteStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ClientId = IDL.Text;
  const Time = IDL.Int;
  const Client = IDL.Record({
    'id' : ClientId,
    'name' : IDL.Text,
    'createdAt' : Time,
    'isActive' : IDL.Bool,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
    'mapLocation' : IDL.Text,
  });
  const FinancialEntryId = IDL.Nat;
  const FinancialEntryType = IDL.Variant({
    'expense' : IDL.Null,
    'income' : IDL.Null,
  });
  const FinancialEntry = IDL.Record({
    'id' : FinancialEntryId,
    'entryType' : FinancialEntryType,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const InvoiceId = IDL.Nat;
  const Invoice = IDL.Record({
    'id' : InvoiceId,
    'clientId' : ClientId,
    'clientName' : IDL.Text,
    'date' : IDL.Text,
    'isPaid' : IDL.Bool,
    'totalAmount' : IDL.Nat,
    'nextMaintenanceDate' : IDL.Text,
    'services' : IDL.Vec(IDL.Text),
  });
  const JobId = IDL.Nat;
  const JobStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Job = IDL.Record({
    'id' : JobId,
    'status' : JobStatus,
    'clientId' : ClientId,
    'clientName' : IDL.Text,
    'date' : IDL.Text,
    'serviceDescription' : IDL.Text,
    'notes' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Garden = IDL.Record({
    'photoUrls' : IDL.Vec(IDL.Text),
    'clientId' : ClientId,
    'toolsRequired' : IDL.Text,
    'grassType' : IDL.Text,
    'sizeM2' : IDL.Float64,
    'observations' : IDL.Text,
    'avgWorkTimeHours' : IDL.Float64,
    'terrainType' : IDL.Text,
  });
  const ScheduleId = IDL.Text;
  const MaintenanceSchedule = IDL.Record({
    'id' : ScheduleId,
    'frequencyDays' : IDL.Nat,
    'clientId' : ClientId,
    'isActive' : IDL.Bool,
    'notes' : IDL.Text,
    'lastDate' : IDL.Text,
    'nextDate' : IDL.Text,
  });
  const ProspectId = IDL.Nat;
  const ProspectStatus = IDL.Variant({
    'quoteSent' : IDL.Null,
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const Prospect = IDL.Record({
    'id' : ProspectId,
    'status' : ProspectStatus,
    'name' : IDL.Text,
    'serviceRequested' : IDL.Text,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
    'quoteDate' : IDL.Text,
  });
  const QuoteId = IDL.Nat;
  const QuoteStatus = IDL.Variant({
    'pending' : IDL.Null,
    'sent' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const Quote = IDL.Record({
    'id' : QuoteId,
    'status' : QuoteStatus,
    'clientId' : ClientId,
    'clientName' : IDL.Text,
    'date' : IDL.Text,
    'serviceDescription' : IDL.Text,
    'notes' : IDL.Text,
    'price' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createClient' : IDL.Func([Client], [], []),
    'createFinancialEntry' : IDL.Func([FinancialEntry], [FinancialEntryId], []),
    'createInvoice' : IDL.Func([Invoice], [InvoiceId], []),
    'createJob' : IDL.Func([Job], [JobId], []),
    'createOrUpdateGarden' : IDL.Func([Garden], [], []),
    'createOrUpdateMaintenanceSchedule' : IDL.Func(
        [MaintenanceSchedule],
        [],
        [],
      ),
    'createProspect' : IDL.Func([Prospect], [ProspectId], []),
    'createQuote' : IDL.Func([Quote], [QuoteId], []),
    'deleteClient' : IDL.Func([ClientId], [], []),
    'deleteFinancialEntry' : IDL.Func([FinancialEntryId], [], []),
    'deleteInvoice' : IDL.Func([InvoiceId], [], []),
    'deleteJob' : IDL.Func([JobId], [], []),
    'deleteProspect' : IDL.Func([ProspectId], [], []),
    'deleteQuote' : IDL.Func([QuoteId], [], []),
    'getAllActiveSchedules' : IDL.Func(
        [],
        [IDL.Vec(MaintenanceSchedule)],
        ['query'],
      ),
    'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getAllJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClient' : IDL.Func([ClientId], [Client], ['query']),
    'getEntriesByType' : IDL.Func(
        [FinancialEntryType],
        [IDL.Vec(FinancialEntry)],
        ['query'],
      ),
    'getGardenByClient' : IDL.Func([ClientId], [Garden], ['query']),
    'getInvoice' : IDL.Func([InvoiceId], [Invoice], ['query']),
    'getJob' : IDL.Func([JobId], [Job], ['query']),
    'getProspectsByStatus' : IDL.Func(
        [ProspectStatus],
        [IDL.Vec(Prospect)],
        ['query'],
      ),
    'getQuoteByStatus' : IDL.Func([QuoteStatus], [IDL.Vec(Quote)], ['query']),
    'getUpcomingMaintenance' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(MaintenanceSchedule)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markInvoiceAsPaid' : IDL.Func([InvoiceId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateClient' : IDL.Func([Client], [], []),
    'updateFinancialEntry' : IDL.Func([FinancialEntry], [], []),
    'updateJob' : IDL.Func([Job], [], []),
    'updateJobStatus' : IDL.Func([JobId, JobStatus], [], []),
    'updateProspect' : IDL.Func([Prospect], [], []),
    'updateProspectStatus' : IDL.Func([ProspectId, ProspectStatus], [], []),
    'updateQuote' : IDL.Func([Quote], [], []),
    'updateQuoteStatus' : IDL.Func([QuoteId, QuoteStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };