/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Client {
  'id' : ClientId,
  'name' : string,
  'createdAt' : Time,
  'isActive' : boolean,
  'address' : string,
  'notes' : string,
  'phone' : string,
  'mapLocation' : string,
}
export type ClientId = string;
export interface FinancialEntry {
  'id' : FinancialEntryId,
  'entryType' : FinancialEntryType,
  'date' : string,
  'description' : string,
  'category' : string,
  'amount' : bigint,
}
export type FinancialEntryId = bigint;
export type FinancialEntryType = { 'expense' : null } |
  { 'income' : null };
export interface Garden {
  'photoUrls' : Array<string>,
  'clientId' : ClientId,
  'toolsRequired' : string,
  'grassType' : string,
  'sizeM2' : number,
  'observations' : string,
  'avgWorkTimeHours' : number,
  'terrainType' : string,
}
export interface Invoice {
  'id' : InvoiceId,
  'clientId' : ClientId,
  'clientName' : string,
  'date' : string,
  'isPaid' : boolean,
  'totalAmount' : bigint,
  'nextMaintenanceDate' : string,
  'services' : Array<string>,
}
export type InvoiceId = bigint;
export interface Job {
  'id' : JobId,
  'status' : JobStatus,
  'clientId' : ClientId,
  'clientName' : string,
  'date' : string,
  'serviceDescription' : string,
  'notes' : string,
  'price' : bigint,
}
export type JobId = bigint;
export type JobStatus = { 'scheduled' : null } |
  { 'cancelled' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface MaintenanceSchedule {
  'id' : ScheduleId,
  'frequencyDays' : bigint,
  'clientId' : ClientId,
  'isActive' : boolean,
  'notes' : string,
  'lastDate' : string,
  'nextDate' : string,
}
export interface Prospect {
  'id' : ProspectId,
  'status' : ProspectStatus,
  'name' : string,
  'serviceRequested' : string,
  'address' : string,
  'notes' : string,
  'phone' : string,
  'quoteDate' : string,
}
export type ProspectId = bigint;
export type ProspectStatus = { 'quoteSent' : null } |
  { 'pending' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export interface Quote {
  'id' : QuoteId,
  'status' : QuoteStatus,
  'clientId' : ClientId,
  'clientName' : string,
  'date' : string,
  'serviceDescription' : string,
  'notes' : string,
  'price' : bigint,
}
export type QuoteId = bigint;
export type QuoteStatus = { 'pending' : null } |
  { 'sent' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export type ScheduleId = string;
export type Time = bigint;
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createClient' : ActorMethod<[Client], undefined>,
  'createFinancialEntry' : ActorMethod<[FinancialEntry], FinancialEntryId>,
  'createInvoice' : ActorMethod<[Invoice], InvoiceId>,
  'createJob' : ActorMethod<[Job], JobId>,
  'createOrUpdateGarden' : ActorMethod<[Garden], undefined>,
  'createOrUpdateMaintenanceSchedule' : ActorMethod<
    [MaintenanceSchedule],
    undefined
  >,
  'createProspect' : ActorMethod<[Prospect], ProspectId>,
  'createQuote' : ActorMethod<[Quote], QuoteId>,
  'deleteClient' : ActorMethod<[ClientId], undefined>,
  'deleteFinancialEntry' : ActorMethod<[FinancialEntryId], undefined>,
  'deleteInvoice' : ActorMethod<[InvoiceId], undefined>,
  'deleteJob' : ActorMethod<[JobId], undefined>,
  'deleteProspect' : ActorMethod<[ProspectId], undefined>,
  'deleteQuote' : ActorMethod<[QuoteId], undefined>,
  'getAllActiveSchedules' : ActorMethod<[], Array<MaintenanceSchedule>>,
  'getAllClients' : ActorMethod<[], Array<Client>>,
  'getAllInvoices' : ActorMethod<[], Array<Invoice>>,
  'getAllJobs' : ActorMethod<[], Array<Job>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClient' : ActorMethod<[ClientId], Client>,
  'getEntriesByType' : ActorMethod<[FinancialEntryType], Array<FinancialEntry>>,
  'getGardenByClient' : ActorMethod<[ClientId], Garden>,
  'getInvoice' : ActorMethod<[InvoiceId], Invoice>,
  'getJob' : ActorMethod<[JobId], Job>,
  'getProspectsByStatus' : ActorMethod<[ProspectStatus], Array<Prospect>>,
  'getQuoteByStatus' : ActorMethod<[QuoteStatus], Array<Quote>>,
  'getUpcomingMaintenance' : ActorMethod<[bigint], Array<MaintenanceSchedule>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markInvoiceAsPaid' : ActorMethod<[InvoiceId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateClient' : ActorMethod<[Client], undefined>,
  'updateFinancialEntry' : ActorMethod<[FinancialEntry], undefined>,
  'updateJob' : ActorMethod<[Job], undefined>,
  'updateJobStatus' : ActorMethod<[JobId, JobStatus], undefined>,
  'updateProspect' : ActorMethod<[Prospect], undefined>,
  'updateProspectStatus' : ActorMethod<[ProspectId, ProspectStatus], undefined>,
  'updateQuote' : ActorMethod<[Quote], undefined>,
  'updateQuoteStatus' : ActorMethod<[QuoteId, QuoteStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];