/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Prospect {
    id: ProspectId;
    status: ProspectStatus;
    name: string;
    serviceRequested: string;
    address: string;
    notes: string;
    phone: string;
    quoteDate: string;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type ProspectId = bigint;
export interface MaintenanceSchedule {
    id: ScheduleId;
    frequencyDays: bigint;
    clientId: ClientId;
    isActive: boolean;
    notes: string;
    lastDate: string;
    nextDate: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type JobId = bigint;
export interface Invoice {
    id: InvoiceId;
    clientId: ClientId;
    clientName: string;
    date: string;
    isPaid: boolean;
    totalAmount: bigint;
    nextMaintenanceDate: string;
    services: Array<string>;
}
export interface Garden {
    photoUrls: Array<string>;
    clientId: ClientId;
    toolsRequired: string;
    grassType: string;
    sizeM2: number;
    observations: string;
    avgWorkTimeHours: number;
    terrainType: string;
}
export type ScheduleId = string;
export type QuoteId = bigint;
export interface Job {
    id: JobId;
    status: JobStatus;
    clientId: ClientId;
    clientName: string;
    date: string;
    serviceDescription: string;
    notes: string;
    price: bigint;
}
export type InvoiceId = bigint;
export type FinancialEntryId = bigint;
export interface FinancialEntry {
    id: FinancialEntryId;
    entryType: FinancialEntryType;
    date: string;
    description: string;
    category: string;
    amount: bigint;
}
export interface Quote {
    id: QuoteId;
    status: QuoteStatus;
    clientId: ClientId;
    clientName: string;
    date: string;
    serviceDescription: string;
    notes: string;
    price: bigint;
}
export interface Client {
    id: ClientId;
    name: string;
    createdAt: Time;
    isActive: boolean;
    address: string;
    notes: string;
    phone: string;
    mapLocation: string;
}
export type ClientId = string;
export interface UserProfile {
    name: string;
    role: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum FinancialEntryType {
    expense = "expense",
    income = "income"
}
export enum JobStatus {
    scheduled = "scheduled",
    cancelled = "cancelled",
    completed = "completed",
    inProgress = "inProgress"
}
export enum ProspectStatus {
    quoteSent = "quoteSent",
    pending = "pending",
    rejected = "rejected",
    accepted = "accepted"
}
export enum QuoteStatus {
    pending = "pending",
    sent = "sent",
    rejected = "rejected",
    accepted = "accepted"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createClient(client: Client): Promise<void>;
    createFinancialEntry(entry: FinancialEntry): Promise<FinancialEntryId>;
    createInvoice(invoice: Invoice): Promise<InvoiceId>;
    createJob(job: Job): Promise<JobId>;
    createOrUpdateGarden(garden: Garden): Promise<void>;
    createOrUpdateMaintenanceSchedule(schedule: MaintenanceSchedule): Promise<void>;
    createProspect(prospect: Prospect): Promise<ProspectId>;
    createQuote(quote: Quote): Promise<QuoteId>;
    deleteClient(clientId: ClientId): Promise<void>;
    deleteFinancialEntry(entryId: FinancialEntryId): Promise<void>;
    deleteInvoice(invoiceId: InvoiceId): Promise<void>;
    deleteJob(jobId: JobId): Promise<void>;
    deleteProspect(prospectId: ProspectId): Promise<void>;
    deleteQuote(quoteId: QuoteId): Promise<void>;
    getAllActiveSchedules(): Promise<Array<MaintenanceSchedule>>;
    getAllClients(): Promise<Array<Client>>;
    getAllInvoices(): Promise<Array<Invoice>>;
    getAllJobs(): Promise<Array<Job>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClient(clientId: ClientId): Promise<Client>;
    getEntriesByType(entryType: FinancialEntryType): Promise<Array<FinancialEntry>>;
    getGardenByClient(clientId: ClientId): Promise<Garden>;
    getInvoice(invoiceId: InvoiceId): Promise<Invoice>;
    getJob(jobId: JobId): Promise<Job>;
    getProspectsByStatus(status: ProspectStatus): Promise<Array<Prospect>>;
    getQuoteByStatus(status: QuoteStatus): Promise<Array<Quote>>;
    getUpcomingMaintenance(days: bigint): Promise<Array<MaintenanceSchedule>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markInvoiceAsPaid(invoiceId: InvoiceId): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateClient(updatedClient: Client): Promise<void>;
    updateFinancialEntry(entry: FinancialEntry): Promise<void>;
    updateJob(job: Job): Promise<void>;
    updateJobStatus(jobId: JobId, status: JobStatus): Promise<void>;
    updateProspect(prospect: Prospect): Promise<void>;
    updateProspectStatus(prospectId: ProspectId, status: ProspectStatus): Promise<void>;
    updateQuote(quote: Quote): Promise<void>;
    updateQuoteStatus(quoteId: QuoteId, status: QuoteStatus): Promise<void>;
}
import type { ClientId as _ClientId, FinancialEntry as _FinancialEntry, FinancialEntryId as _FinancialEntryId, FinancialEntryType as _FinancialEntryType, Job as _Job, JobId as _JobId, JobStatus as _JobStatus, Prospect as _Prospect, ProspectId as _ProspectId, ProspectStatus as _ProspectStatus, Quote as _Quote, QuoteId as _QuoteId, QuoteStatus as _QuoteStatus, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createClient(arg0: Client): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClient(arg0);
            return result;
        }
    }
    async createFinancialEntry(arg0: FinancialEntry): Promise<FinancialEntryId> {
        if (this.processError) {
            try {
                const result = await this.actor.createFinancialEntry(to_candid_FinancialEntry_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFinancialEntry(to_candid_FinancialEntry_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createInvoice(arg0: Invoice): Promise<InvoiceId> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvoice(arg0);
            return result;
        }
    }
    async createJob(arg0: Job): Promise<JobId> {
        if (this.processError) {
            try {
                const result = await this.actor.createJob(to_candid_Job_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJob(to_candid_Job_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createOrUpdateGarden(arg0: Garden): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateGarden(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateGarden(arg0);
            return result;
        }
    }
    async createOrUpdateMaintenanceSchedule(arg0: MaintenanceSchedule): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateMaintenanceSchedule(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateMaintenanceSchedule(arg0);
            return result;
        }
    }
    async createProspect(arg0: Prospect): Promise<ProspectId> {
        if (this.processError) {
            try {
                const result = await this.actor.createProspect(to_candid_Prospect_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProspect(to_candid_Prospect_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createQuote(arg0: Quote): Promise<QuoteId> {
        if (this.processError) {
            try {
                const result = await this.actor.createQuote(to_candid_Quote_n22(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createQuote(to_candid_Quote_n22(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteClient(arg0: ClientId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClient(arg0);
            return result;
        }
    }
    async deleteFinancialEntry(arg0: FinancialEntryId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFinancialEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFinancialEntry(arg0);
            return result;
        }
    }
    async deleteInvoice(arg0: InvoiceId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInvoice(arg0);
            return result;
        }
    }
    async deleteJob(arg0: JobId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJob(arg0);
            return result;
        }
    }
    async deleteProspect(arg0: ProspectId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProspect(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProspect(arg0);
            return result;
        }
    }
    async deleteQuote(arg0: QuoteId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteQuote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteQuote(arg0);
            return result;
        }
    }
    async getAllActiveSchedules(): Promise<Array<MaintenanceSchedule>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActiveSchedules();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActiveSchedules();
            return result;
        }
    }
    async getAllClients(): Promise<Array<Client>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClients();
            return result;
        }
    }
    async getAllInvoices(): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInvoices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInvoices();
            return result;
        }
    }
    async getAllJobs(): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJobs();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJobs();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClient(arg0: ClientId): Promise<Client> {
        if (this.processError) {
            try {
                const result = await this.actor.getClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClient(arg0);
            return result;
        }
    }
    async getEntriesByType(arg0: FinancialEntryType): Promise<Array<FinancialEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEntriesByType(to_candid_FinancialEntryType_n12(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEntriesByType(to_candid_FinancialEntryType_n12(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGardenByClient(arg0: ClientId): Promise<Garden> {
        if (this.processError) {
            try {
                const result = await this.actor.getGardenByClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGardenByClient(arg0);
            return result;
        }
    }
    async getInvoice(arg0: InvoiceId): Promise<Invoice> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoice(arg0);
            return result;
        }
    }
    async getJob(arg0: JobId): Promise<Job> {
        if (this.processError) {
            try {
                const result = await this.actor.getJob(arg0);
                return from_candid_Job_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJob(arg0);
            return from_candid_Job_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProspectsByStatus(arg0: ProspectStatus): Promise<Array<Prospect>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProspectsByStatus(to_candid_ProspectStatus_n20(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProspectsByStatus(to_candid_ProspectStatus_n20(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuoteByStatus(arg0: QuoteStatus): Promise<Array<Quote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuoteByStatus(to_candid_QuoteStatus_n24(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuoteByStatus(to_candid_QuoteStatus_n24(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUpcomingMaintenance(arg0: bigint): Promise<Array<MaintenanceSchedule>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUpcomingMaintenance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUpcomingMaintenance(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markInvoiceAsPaid(arg0: InvoiceId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markInvoiceAsPaid(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markInvoiceAsPaid(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateClient(arg0: Client): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClient(arg0);
            return result;
        }
    }
    async updateFinancialEntry(arg0: FinancialEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFinancialEntry(to_candid_FinancialEntry_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFinancialEntry(to_candid_FinancialEntry_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateJob(arg0: Job): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJob(to_candid_Job_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJob(to_candid_Job_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateJobStatus(arg0: JobId, arg1: JobStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJobStatus(arg0, to_candid_JobStatus_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJobStatus(arg0, to_candid_JobStatus_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateProspect(arg0: Prospect): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProspect(to_candid_Prospect_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProspect(to_candid_Prospect_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateProspectStatus(arg0: ProspectId, arg1: ProspectStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProspectStatus(arg0, to_candid_ProspectStatus_n20(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProspectStatus(arg0, to_candid_ProspectStatus_n20(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateQuote(arg0: Quote): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateQuote(to_candid_Quote_n22(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateQuote(to_candid_Quote_n22(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateQuoteStatus(arg0: QuoteId, arg1: QuoteStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateQuoteStatus(arg0, to_candid_QuoteStatus_n24(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateQuoteStatus(arg0, to_candid_QuoteStatus_n24(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_FinancialEntryType_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FinancialEntryType): FinancialEntryType {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_FinancialEntry_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FinancialEntry): FinancialEntry {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_JobStatus_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobStatus): JobStatus {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Job_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Job): Job {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_ProspectStatus_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProspectStatus): ProspectStatus {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_Prospect_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Prospect): Prospect {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_QuoteStatus_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuoteStatus): QuoteStatus {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_Quote_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Quote): Quote {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _JobId;
    status: _JobStatus;
    clientId: _ClientId;
    clientName: string;
    date: string;
    serviceDescription: string;
    notes: string;
    price: bigint;
}): {
    id: JobId;
    status: JobStatus;
    clientId: ClientId;
    clientName: string;
    date: string;
    serviceDescription: string;
    notes: string;
    price: bigint;
} {
    return {
        id: value.id,
        status: from_candid_JobStatus_n29(_uploadFile, _downloadFile, value.status),
        clientId: value.clientId,
        clientName: value.clientName,
        date: value.date,
        serviceDescription: value.serviceDescription,
        notes: value.notes,
        price: value.price
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _FinancialEntryId;
    entryType: _FinancialEntryType;
    date: string;
    description: string;
    category: string;
    amount: bigint;
}): {
    id: FinancialEntryId;
    entryType: FinancialEntryType;
    date: string;
    description: string;
    category: string;
    amount: bigint;
} {
    return {
        id: value.id,
        entryType: from_candid_FinancialEntryType_n37(_uploadFile, _downloadFile, value.entryType),
        date: value.date,
        description: value.description,
        category: value.category,
        amount: value.amount
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProspectId;
    status: _ProspectStatus;
    name: string;
    serviceRequested: string;
    address: string;
    notes: string;
    phone: string;
    quoteDate: string;
}): {
    id: ProspectId;
    status: ProspectStatus;
    name: string;
    serviceRequested: string;
    address: string;
    notes: string;
    phone: string;
    quoteDate: string;
} {
    return {
        id: value.id,
        status: from_candid_ProspectStatus_n42(_uploadFile, _downloadFile, value.status),
        name: value.name,
        serviceRequested: value.serviceRequested,
        address: value.address,
        notes: value.notes,
        phone: value.phone,
        quoteDate: value.quoteDate
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _QuoteId;
    status: _QuoteStatus;
    clientId: _ClientId;
    clientName: string;
    date: string;
    serviceDescription: string;
    notes: string;
    price: bigint;
}): {
    id: QuoteId;
    status: QuoteStatus;
    clientId: ClientId;
    clientName: string;
    date: string;
    serviceDescription: string;
    notes: string;
    price: bigint;
} {
    return {
        id: value.id,
        status: from_candid_QuoteStatus_n47(_uploadFile, _downloadFile, value.status),
        clientId: value.clientId,
        clientName: value.clientName,
        date: value.date,
        serviceDescription: value.serviceDescription,
        notes: value.notes,
        price: value.price
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduled: null;
} | {
    cancelled: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): JobStatus {
    return "scheduled" in value ? JobStatus.scheduled : "cancelled" in value ? JobStatus.cancelled : "completed" in value ? JobStatus.completed : "inProgress" in value ? JobStatus.inProgress : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expense: null;
} | {
    income: null;
}): FinancialEntryType {
    return "expense" in value ? FinancialEntryType.expense : "income" in value ? FinancialEntryType.income : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    quoteSent: null;
} | {
    pending: null;
} | {
    rejected: null;
} | {
    accepted: null;
}): ProspectStatus {
    return "quoteSent" in value ? ProspectStatus.quoteSent : "pending" in value ? ProspectStatus.pending : "rejected" in value ? ProspectStatus.rejected : "accepted" in value ? ProspectStatus.accepted : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    sent: null;
} | {
    rejected: null;
} | {
    accepted: null;
}): QuoteStatus {
    return "pending" in value ? QuoteStatus.pending : "sent" in value ? QuoteStatus.sent : "rejected" in value ? QuoteStatus.rejected : "accepted" in value ? QuoteStatus.accepted : value;
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Job>): Array<Job> {
    return value.map((x)=>from_candid_Job_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FinancialEntry>): Array<FinancialEntry> {
    return value.map((x)=>from_candid_FinancialEntry_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Prospect>): Array<Prospect> {
    return value.map((x)=>from_candid_Prospect_n40(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Quote>): Array<Quote> {
    return value.map((x)=>from_candid_Quote_n45(_uploadFile, _downloadFile, x));
}
function to_candid_FinancialEntryType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FinancialEntryType): _FinancialEntryType {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_FinancialEntry_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FinancialEntry): _FinancialEntry {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_JobStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobStatus): _JobStatus {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_Job_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Job): _Job {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_ProspectStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProspectStatus): _ProspectStatus {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_Prospect_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Prospect): _Prospect {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_QuoteStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuoteStatus): _QuoteStatus {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_Quote_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Quote): _Quote {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: FinancialEntryId;
    entryType: FinancialEntryType;
    date: string;
    description: string;
    category: string;
    amount: bigint;
}): {
    id: _FinancialEntryId;
    entryType: _FinancialEntryType;
    date: string;
    description: string;
    category: string;
    amount: bigint;
} {
    return {
        id: value.id,
        entryType: to_candid_FinancialEntryType_n12(_uploadFile, _downloadFile, value.entryType),
        date: value.date,
        description: value.description,
        category: value.category,
        amount: value.amount
    };
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: JobId;
    status: JobStatus;
    clientId: ClientId;
    clientName: string;
    date: string;
    serviceDescription: string;
    notes: string;
    price: bigint;
}): {
    id: _JobId;
    status: _JobStatus;
    clientId: _ClientId;
    clientName: string;
    date: string;
    serviceDescription: string;
    notes: string;
    price: bigint;
} {
    return {
        id: value.id,
        status: to_candid_JobStatus_n16(_uploadFile, _downloadFile, value.status),
        clientId: value.clientId,
        clientName: value.clientName,
        date: value.date,
        serviceDescription: value.serviceDescription,
        notes: value.notes,
        price: value.price
    };
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ProspectId;
    status: ProspectStatus;
    name: string;
    serviceRequested: string;
    address: string;
    notes: string;
    phone: string;
    quoteDate: string;
}): {
    id: _ProspectId;
    status: _ProspectStatus;
    name: string;
    serviceRequested: string;
    address: string;
    notes: string;
    phone: string;
    quoteDate: string;
} {
    return {
        id: value.id,
        status: to_candid_ProspectStatus_n20(_uploadFile, _downloadFile, value.status),
        name: value.name,
        serviceRequested: value.serviceRequested,
        address: value.address,
        notes: value.notes,
        phone: value.phone,
        quoteDate: value.quoteDate
    };
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: QuoteId;
    status: QuoteStatus;
    clientId: ClientId;
    clientName: string;
    date: string;
    serviceDescription: string;
    notes: string;
    price: bigint;
}): {
    id: _QuoteId;
    status: _QuoteStatus;
    clientId: _ClientId;
    clientName: string;
    date: string;
    serviceDescription: string;
    notes: string;
    price: bigint;
} {
    return {
        id: value.id,
        status: to_candid_QuoteStatus_n24(_uploadFile, _downloadFile, value.status),
        clientId: value.clientId,
        clientName: value.clientName,
        date: value.date,
        serviceDescription: value.serviceDescription,
        notes: value.notes,
        price: value.price
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FinancialEntryType): {
    expense: null;
} | {
    income: null;
} {
    return value == FinancialEntryType.expense ? {
        expense: null
    } : value == FinancialEntryType.income ? {
        income: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobStatus): {
    scheduled: null;
} | {
    cancelled: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == JobStatus.scheduled ? {
        scheduled: null
    } : value == JobStatus.cancelled ? {
        cancelled: null
    } : value == JobStatus.completed ? {
        completed: null
    } : value == JobStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProspectStatus): {
    quoteSent: null;
} | {
    pending: null;
} | {
    rejected: null;
} | {
    accepted: null;
} {
    return value == ProspectStatus.quoteSent ? {
        quoteSent: null
    } : value == ProspectStatus.pending ? {
        pending: null
    } : value == ProspectStatus.rejected ? {
        rejected: null
    } : value == ProspectStatus.accepted ? {
        accepted: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuoteStatus): {
    pending: null;
} | {
    sent: null;
} | {
    rejected: null;
} | {
    accepted: null;
} {
    return value == QuoteStatus.pending ? {
        pending: null
    } : value == QuoteStatus.sent ? {
        sent: null
    } : value == QuoteStatus.rejected ? {
        rejected: null
    } : value == QuoteStatus.accepted ? {
        accepted: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
